### ISSUE TITLE
Online text editor support?

### ISSUE THREAD

**Issue by kirbyzhou** [websvnphp/websvn#100]
May websvn integrate an online web editor even without markdown support?
It will be very useful when we need to do little changes to config file or README.

**Comment by ams-tschoening** [comment]
In my opinion it's pretty unlikely that such feature gets implemented, because 1. WebSVN focuses on browsing and read-only access mostly and 2. unless you are implementing this on your own, most likely nobody else will.

Online editing easily gets complex as well: It's not only about some textual input box, but people easily expect that draft changes will be saved automatically in the background, syntax highlighting, one might need to deal with different indentation for different code styles, concurrent modifications of the same file etc.

I don't think that such collaboration will ever find its way into WebSVN and you might better look for different workflows and tools if you really need this.

**Comment by michael-o** [comment]
I fully agree with @ams-tschoening. I'd even close this one for explicitly not wanted.
