### ISSUE TITLE
In Listing View Cannot Open Two Directories in a Tree View for Comparison

### ISSUE THREAD

**Issue by k10blogger** [websvnphp/websvn#104]
One of the most commonly used feature atleast for me is the compare paths in the listing view. 

The issue is, it is not possible in the listing view to compare same file across multiple tags or branches or even in different folders in a same tag. 

For example consider below two directories under tags(as seen in image).
[1] and [2] as in image attached.
As [2] is open i can see files within it. But if i have to compare it with files in [1] I cannot use this UI for comparison as when i open the folder [1] the folder [2] closes.

![image](https://user-images.githubusercontent.com/4973182/82509255-f46af680-9b24-11ea-9e3e-d55a1b68f524.png)

Things are not better when i select a file in tag and try to compare it with one in trunk. As soon as i click on the trunk folder the tag folder closes. 

Anyway of fixing this?

**Comment by ams-tschoening** [comment]
I don' think so, WebSVN is a pretty old-school web app requesting one path only and NOT storing any former state AFAICS. The latter would be what you need to compare arbitrary paths. Looking a bit into things, here is how I think showing the current directory works:

Consider a path `/foo/bar` requested, than contents of `/`, `/foo` and `/foo/bar` get build and rendered, in the order. What you would need to have is somehow remembering the path your are interested in besides the current directory and render that pretty much the same way like the current directory. Afterwards providing all those pieces to the template engine.

Besides thinking of some way to have the former path to compare with still available, this requires heavy refactoring of `listing.php`. It assumes to be called with the current directory only and relies heavily on globally available variables.

I'm attaching some PoC of how things need to be changed, but don't have the time to work more on this. What's currently especially not working is rendering contents for each path, because some index is used and most likely places things at the same places at some point or such. When trying two different paths, the template show some parts doubled and some parts of the latter of the two paths only.

[listing_with_two_paths.patch.txt](https://github.com/websvnphp/websvn/files/4661886/listing_with_two_paths.patch.txt)
[listing.php.txt](https://github.com/websvnphp/websvn/files/4661887/listing.php.txt)

**Comment by k10blogger** [comment]
Hi I have been working on this but not had much success. I first learned php for 10-15 days but whatever i learnt had no implementation here. 

I implemented what you mentioned [here](https://github.com/k10blogger/websvn/commit/76d25be68efe37188740b57fa5a037448277aa31). This can be expanded for n number of path. 

The only thing i couldnt do was merge the two list to form one coherent list. In SVN too if we give two path and get the xml log we get two SVNLIST object. 
Can you suggest some thing to me on how to merge the two list to have one coherent list?
The output comes one after the other.
![image](https://user-images.githubusercontent.com/4973182/85320939-7e6dfc80-b4e1-11ea-8b0f-db3979cab7b2.png)
