### ISSUE TITLE
Feature Request - Add an option to Map Samba Drives to work with websvn

### ISSUE THREAD

**Issue by k10blogger** [websvnphp/websvn#118]
As of now if I need to access repositories stored on the network drives i need to run the apache service hosting websvn with that accessible username.

What i am requesting is to optionally add network mounting in the websvn someway in configuration class or someplace to be used in config.php as an optional setting.

Right now i use something like the following in the config.php file that works for me.
```
exec('net use G: "\\\\server\\mountfolder" /user:"domain-userid" "domainpassword" /persistence:no');
$config->addRepository('Name to Display','file:///G://path//to//repos//');
```

Maybe this is a one off use case in my scenario where i need to host all repository from a single sever where repos are stored in multiple geographical areas in different drives. But still a good feature to have optionally.

**Comment by ams-tschoening** [comment]
Please provide more details about your concrete setup, which OS hosts the SVN-repos how, where does WebSVN+HTTPd run etc. It seems WebSVN is running on Windows, while the repos are placed at least on different machines, but most likely Windows as well?

This is important to know, because especially Windows-clients resolve different protocols automatically. I have some Java and Gradle-based build publishing to some SMB-share hosted on some Ubuntu-Linux and the only thing I need to do in Windows is using the following `file:`-URL:

> file://HOST/SHARE

When executed, Windows internally automatically resolves that URL to be a SMB share and accesses that using my credentials for that share and stuff like that. NO need to mount things manually to some letter. Did you already try something like that with your repos? I would expect that this works for multiple hosts and shares the same way.

Getting some OS-independent "mount"-concept right seems somewhat difficult to me. In the end it comes down to be some `exec` like you have, but with either `net use` or `mount`, depending on the OS. I don't see too much benefit in adding something that unspecific to WebSVN currently. OTOH, it can't become too specific, because mount sources and targets etc. are pretty different most likely, so one would need to introduce configs for those, document those etc., to ultimately only build some command line to `exec` again.

So it might be easier to let people with such a use case customize things like you did already. If they simply deploy using GIT, they can keep track of their customizations easily and include updates from UPSTREAM easily as well, in the worst case with GIT's support for resolving conflicts etc. Might be easier for those users than for us to maintain some "mount"-concept.

**Comment by ams-tschoening** [comment]
Please provide more details about your concrete setup, which OS hosts the SVN-repos how, where does WebSVN+HTTPd run etc. It seems WebSVN is running on Windows, while the repos are placed at least on different machines, but most likely Windows as well?

This is important to know, because especially Windows-clients resolve different protocols automatically. I have some Java and Gradle-based build publishing to some SMB-share hosted on some Ubuntu-Linux and the only thing I need to do in Windows is using the following `file:`-URL:

> file://HOST/SHARE

When executed, Windows internally automatically resolves that URL to be a SMB share and accesses that using my credentials for that share and stuff like that. NO need to mount things manually to some letter. Did you already try something like that with your repos? I would expect that this works for multiple hosts and shares the same way.

Besides that, keep in mind that many SVN-devs discourage using repos on network shares at all:

> In fact we would strongly discourage it, and do not support such use for various reasons:

https://tortoisesvn.net/docs/release/TortoiseSVN_en/tsvn-repository.html#tsvn-repository-local-share

> If you need to store your repositories on a remote disk for some specific reason, then we strongly recommend using either iSCSI storage or a block-level virtual drive disk. If neither of these options are available, the repositories may be stored on a network share, although doing so will most likely introduce a performance penalty. Note that when using the network share you have to check the version of the SMB protocol, because using unsupported version may lead to data corruption.

https://www.visualsvn.com/support/topic/00022/

Did you have a look at WebDAV already? SVN-repos can be exported using HTTP and accessed by all SVN-clients using that protocol as well. So you might even consider exporting your repos using mod_dav_svn and Apache HTTPd instead of using SMB-shares. This prevents you from the need to mount some shares entirely and it seems you are already somewhat familiar with using Apache HTTPd.

I would even give the `svn://`-protocol a try by running `svnserve`. In theory only the SVN-client used by WebSVN should need to handle those protocols and those clearly support that. So if WebSVN doesn't care too much about the individual protocols, but only stores them as strings at most places, even `svnserve` might work.

Getting some OS-independent "mount"-concept right seems somewhat difficult to me. In the end it comes down to be some `exec` like you have, but with either `net use` or `mount`, depending on the OS. I don't see too much benefit in adding something that unspecific to WebSVN currently. OTOH, it can't become too specific, because mount sources and targets etc. are pretty different most likely, so one would need to introduce configs for those, document those etc., to ultimately only build some command line to `exec` again.

So it might be easier to let people with such a use case customize things like you did already. If they simply deploy using GIT, they can keep track of their customizations easily and include updates from UPSTREAM easily as well, in the worst case with GIT's support for resolving conflicts etc. Might be easier for those users than for us to maintain some "mount"-concept.

**Comment by michael-o** [comment]
I am reluctant to Admin tasks (mount FS) into WebSVN. This is definitively a wrong place. As @ams-tschoening pointed out: use `mod_dav_svn`. There is no reason to use SMB for that.

**Comment by k10blogger** [comment]
@ams-tschoening this is a really great explanation. 
I am actually using the mod_dav_svn and currently before this instance the websvn was accessing the repository over `https:`

The issue for me is that somehow websvn access to `https` as compared to `file://` mount of network shared drive. 
I tried to trace the route for this. Both  have equal firewall hops so not sure what is slowing the `https;//` access down.
Possible we have a caching mechanism for network drives. So on repeated access the performance of `file://` protocol is better, But that is a guess.

I tried doing this:

> file://HOST/SHARE

But the issue here is that the apache httpd service that is running is running on a different domain userid that doesnt have access to other network share. So a solution was needed that can mount network drives with different user credentials. Hence this solution.

The SMB protocol version we are using is version 2. We are using `iSCSI` storage. They are in raid configuration. So we are good atleast in that part. We have some good number of svn repository that are spread over 5 different network drives spread over 5 different continents. The aim is to have one common viewer for all the hosted repos. This is where websvn comes in picture there.

> Getting some OS-independent "mount"-concept right seems somewhat difficult to me. In the end it comes down to be some exec like you have, but with either net use or mount, depending on the OS. I don't see too much benefit in adding something that unspecific to WebSVN currently. OTOH, it can't become too specific, because mount sources and targets etc. are pretty different most likely, so one would need to introduce configs for those, document those etc., to ultimately only build some command line to exec again.

Honestly i did not think of this. Now that i think of it this is very true. As my environment is very windows specific doesn't guarantee that most environment will be. I did a search whether php native support network drive access which is not the case. So in the end if we have to use `exec` command it makes no sense to integrate in websvn. I was hoping you guys would have some native way of doing this in PHP. :) 

But we should see if it is beneficial in other ways i havent think of. Because for my use i already have a solution that i use and get away with in the confi.php file.

**Comment by ams-tschoening** [comment]
While I would expect `https:` to be a little slower than `file:`, I wouldn't expect it to be unusable slow. So you most likely have a problem somewhere, but I would focus on things like DNS, [remote host lookups](https://httpd.apache.org/docs/2.4/mod/core.html#hostnamelookups) done by the HTTPd automatically sometimes etc. Too bad...

Did you try `svnserve` as well?

**Comment by k10blogger** [comment]
yeah it seems that way. I checked this DNS look up part. It is turned off. So that doesnt seem to be a problem either.  

I do not know why we have not tried out `svnserve` before. My assumption was it didnt work. But i will take a look at that. 

What i also did today was asked around the other teams in my organization that uses subversion. They did suggested that i am using an active directory account for subversion in the scenario where the repository response of websvn is slow. So i need to check that out as well. Different servers on different locations seemed to be having different response times to the active directory server.
They also have a single dedicated server with no distribution. So they couldnt relate to the scenario i presented. 

So I think this is indeed a one off case so i guess we should treat it like that.

**Comment by michael-o** [comment]
@michael-o I have now been running `mod_dav_svn` on FreeBSD with SPNEGO authentication for all AD users for almost 8 years now. When you checkout local, it is really fast. You need to start digging.

**Comment by ams-tschoening** [comment]
Closing here for now as per outcome of the former discussion. Until a more widespread use case gets presented, we shouldn't implement those things, because they are too specific. Like described above, users can easily customize such things in their own fork of WebSVN as they see fit as well. Feel free to provide further hints and ideas how to handle such things, they will be found by users and might be worth at some point adding in the wiki oder on the homepage of the project.
