### ISSUE TITLE
Feature Request - File Search Feature #119

### ISSUE THREAD

**Issue by k10blogger** [websvnphp/websvn#119]
I have a suggestion here that i would like to discuss. I would like to propose a File Search Feature. #119 
This searches only for files with some name in the directory and this is not a content search.

How we normally do this right now is using the following command(Windows Only):
(Note: I have repos on network drive hence the path looks UNC style. In normal case it will look like a normal windows path)
```
C:\Windows>svnlook tree --full-paths "\\path_to_repos\svn\repos\EOS" | find "LifeSign"
branches/general/BaseDevice/gaLibTestScripts/LifeSignSv_UDI.py
branches/general/BaseDevice/gaLibTestScripts/LifeSignSv_UI.py
tags/gaLibTestScripts_0.6.0.1_01_12_2019/LifeSignSv_UDI.py
tags/gaLibTestScripts_0.6.0.1_01_12_2019/LifeSignSv_UI.py
tags/gaLibTestScripts_1.0.0.0_05_06_2020/LifeSignSv_UDI.py
tags/gaLibTestScripts_1.0.0.0_05_06_2020/LifeSignSv_UI.py
tags/gaLibTestScripts_1.0.0.99_27_04_2020/LifeSignSv_UDI.py
tags/gaLibTestScripts_1.0.0.99_27_04_2020/LifeSignSv_UI.py
trunk/BaseDevice/gaLibTestScripts/LifeSignSv_UDI.py
trunk/BaseDevice/gaLibTestScripts/LifeSignSv_UI.py
```

For unix system it would look something like this (uses grep):
```
svnlook tree --full-pahts "\\path_to_repos\svn\repos" | grep "LifeSign"
```

The advantage of this is multi fold.
1 - It is that all available paths where the files are there are listed in a single view.
2 - Using the existing compare feature i can just select the two files i want to see and do a compare.
3 - This can be used to list the entire directory in tree view as we have an open issue #104 

The disadvantage of this is also multi fold.
1 - **It is available only where the WebSVN has a direct repository access and not a URL access**. The reason for this is that the command that is used is `svnlook tree` that only works with direct access repos and not URL access. 
2 - I am not sure about the performance penalty if any. I have small size repos only 4-10 GBs. So it is very very fast. 
But i am not sure in scenarios of huge repositories.But as it is a native command so hopefully should be fine.

I have added the snapshot from the svn book. 
![image](https://user-images.githubusercontent.com/4973182/90973853-84b14100-e543-11ea-83c8-7bd3128af0c0.png)

**Comment by k10blogger** [comment]
So i took some time and worked on this. But now we need to discuss where to place and how to arrange the data. 
Here is a summary and key points of how the search bar works and looks. I have added variables in english languages so if we need to extend for others we can do the same.

1. The search bar comes only if the repository is added as local (file:///) not in http as the svnlook command doesnt work with the URL. 
2. Search can be limited to the current path browsed in the directory view. But for now it searches the entire directory. (To be disccussed. Will the user would want to search the entire directory all the time or only the path the user is on??)
3. For now the search only shows in the directory view. (To be discussed if to be added to file or comparison view as well)
![image](https://user-images.githubusercontent.com/4973182/91652409-c185b680-eab4-11ea-8202-b6e23e1a4978.png)
4. A blank search returns the entire directory tree (To be discussed reject the blank search?)
![image](https://user-images.githubusercontent.com/4973182/91652526-e2024080-eab5-11ea-83c2-f9639e8a5691.png)
5. 1. - The search resulted is listed in same way as directory template. But  a new search template has been added. 
    2. - I had to remove revision as the revision is fetched as 
    3. - I think log and RSS should still work but i am not able to get it working for this commit. It seems to be the path i have transferred is missing some revision parameters.
![image](https://user-images.githubusercontent.com/4973182/91652546-1a098380-eab6-11ea-8feb-167ad786c5c0.png)
6. For the text for which it cannot find files shows the error as follow:
![image](https://user-images.githubusercontent.com/4973182/91652631-bdf32f00-eab6-11ea-8317-e6f4e8c850dd.png)
7. For text it finds it list all the files and folders as this:
![image](https://user-images.githubusercontent.com/4973182/91652662-0ad70580-eab7-11ea-9f52-acfd6f35ab33.png)
8. I wish for compare to still work as we do have all the absolute paths of files that are listed. Though still working on revision. But for now the compare in this view is broken. Working on fixing it.( To be discussed. It seems revision is absolutely needed for this comparison to work. )
![image](https://user-images.githubusercontent.com/4973182/91652694-4bcf1a00-eab7-11ea-92fd-617e0c5f9c5f.png)
9. There is still some discrepancy which i am working on like the blanks that come at the bottom. 
![image](https://user-images.githubusercontent.com/4973182/91652729-92247900-eab7-11ea-814d-430ecbe1b703.png)

**Comment by michael-o** [comment]
Will take a look next week

**Comment by ams-tschoening** [comment]
> 2. Search can be limited to the current path browsed in the directory view. But for now it searches the entire directory. (To be disccussed. Will the user would want to search the entire directory all the time or only the path the user is on??)

Users want to choose in the long term, so they can change their mind and search according different criteria. For a good start, it might be best to let performance decide about the default behaviour: If it's awfully slow in most cases when searching fully recursive, simply don't do it or the search won't be used most of the time anyway. If performance is somewhat acceptable for a fully recursive search in most cases, than do that, because that is like most searches behave anyway from my experience.

> 3. For now the search only shows in the directory view. (To be discussed if to be added to file or comparison view as well)

Directory view looks totally fine to me, especially because of the former question: If the search is NOT fully recursive by default, users need a fast way to get to the directory they want to search in anyway. In the long term, searches are added simply everywhere for everything. Just look at desktops, browsers etc. Many of those model some unified search in the long term.

> 4. A blank search returns the entire directory tree (To be discussed reject the blank search?)

Doesn't seem like a priority to me: Rejecting requires more work for you, while an empty search doesn't break things. Improve later, when you have experiences from your own users and leave as-is until then.

> I had to remove revision as the revision is fetched as
> I think log and RSS should still work but i am not able to get it working for this commit. It seems to be the path i have transferred is missing some revision parameters.

Not sure if I understand those problems, but how about simply falling back to HEAD or something known like that?

> For now i have a separate search.php and html search template (search.tmpl) to handle the search data.
> [...]I separated them out as i needed the directory listing to work as intended for now.[...]

That's the correct thing to do, keep it that way. I'm somewhat sure we don't want to merge things and increase file sizes and their complexity etc. in the long term, but maintain individual files/modules/... instead. Integration needs to be provided differently, not by moving the code from one dedicated file into another solving a different purpose originally. We can have a look at those things if you actually provide PRs with what you expect to be working for you.
