### ISSUE TITLE
Change cookies to session only and remove paths?

### ISSUE THREAD

**Issue by ams-tschoening** [websvnphp/websvn#124]
The site uses calls like the following to store two cookies:

	setcookie('storedlang', $language, time() + (60 * 60 * 24 * 356 * 10), '/');
	setcookie('storedsesslang', $language);

	setcookie('storedtemplate', $template, time() + (60 * 60 * 24 * 365 * 10), '/');
	setcookie('storedsesstemplate', $template);

I've checked the history why for each value two cookies are set and the only reason is to have that value available most likely in case users have their browser configured to prevent long time cookies:

> // Override this with the user choice if there is one, and memorise the setting
> // as a cookie (since we don't have user accounts, we can't store the setting
> // anywhere else).  We try to memorise a permanant cookie and a per session cookie
> // in case the user's disabled permanant ones.

https://github.com/websvnphp/websvn/commit/be9ced686cb43180500365be8c866053a2722dc5#diff-f08e511b493e1780d6974ef34a09c477R275

I don't think we need to go that extra step and didn't see that elsewhere. If users don't want cookies, let them be, we don't need to care and maintain two values in my opinion.

Additionally, path handling is inconsistent and especially setting one to '/' makes that cookie be sent too ALL sites published by e.g. `http://localhost/app_1|app_2|...`. Path handling should be left to PHP, which uses the current request directory. If that doesn't work properly, the session-cookie doesn't make any sense at all and the attached screenshot show it does work.

So I suggest switching to a session-cookie only and remove explicit path handling in favour of PHP-defaults. Thoughts?

![Clipboard01](https://user-images.githubusercontent.com/6223655/93603681-a2e45280-f9c4-11ea-90b2-ac94a6475732.png)

**Comment by k10blogger** [comment]
Yeah agreed. Let php handle the path and keep only session only cookies. 

What do you think about using the browser preferred language as an initial language? Most browser nowadays have language preference, would be good use it instead of the using our own cookies? We would be able to change the language any point in time.

**Comment by ams-tschoening** [comment]
Do you suggest removing the lang-cookie entirely or really only change the initial value? I've read PROs and CONs about both already, some people simply argue to let the browser maintain all of that instead of the site.

OTOH, I'm using a browser with German language by default and am glad if some sites like MSDN allow me to store English instead of reading automatically translated English to German or need to reconfigure the browser.

Does WebSVN handle calculating languages by browser-values already? Does PHP do something automatically? I needed to implement something on my own in the past based on `HTTP_ACCEPT_LANGUAGE`.

    if (!empty($_REQUEST['language'])) {

https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4

**Comment by k10blogger** [comment]
Yeah i am thinking of removing the lang-cookie entirely. Lang can be made a global variable that starts with the browser preference and then can be changed by user from the websvn. The reason for my thought process was we do support multiple languages so let browser handle it.

But i do see your point in change in preference from the browser. For that we already have a language selection in the websvn so that variable is still global so in theory it would work by starting the default browser language as default and then user can change the language from the websvn. 

The php too uses this exact same thing `Accept-Language` header. This is the link to that standard.  We need to use something like this `$_SERVER['HTTP_ACCEPT_LANGUAGE']`

**Comment by ams-tschoening** [comment]
I've created #125 for this discussion, those are two separate problems in the end.

**Comment by ams-tschoening** [comment]
I wasn't too sure about if it's really a good idea to only work with session cookies or permanent ones only, so simply changed the path-thing only right now.

https://github.com/websvnphp/websvn/commit/492b0ace20c77745e5ce31bdf620ab46531446a8
