### ISSUE TITLE
Improving 404 Display Page

### ISSUE THREAD

**Issue by k10blogger** [websvnphp/websvn#126]
404 Error is used in scenarios where $repo is not found. But there is no proper template to handle it. This is how it looks if 404 is invoked.
![image](https://user-images.githubusercontent.com/4973182/94358153-9cd52c80-00bc-11eb-80ff-e5cab8e640e6.png)

My proposal is to have a 404 page put in.

**Comment by ams-tschoening** [comment]
For the time being, it MIGHT be an idea as well to NOT print any template at all, but really only answer with status code 404. All browsers provide an error message in those cases anyway. While that message doesn't look like WebSVN, it might be more standard than the screenshotted broken template. Another benefit is that `renderTemplateNoRepo` wouldn't need any argument at all anymore just to render broken stuff which doesn't mention the concrete problem anyway.

**Comment by k10blogger** [comment]
What about using the inbuilt error div tag in the templates
Such as this for calm
![image](https://user-images.githubusercontent.com/4973182/95019613-f07ae380-0683-11eb-8c1c-962ea8d453d0.png)
This for bluegrey
![image](https://user-images.githubusercontent.com/4973182/95019626-04bee080-0684-11eb-80a8-62a74587428f.png)
This for elegant
![image](https://user-images.githubusercontent.com/4973182/95019633-13a59300-0684-11eb-954e-cf503a0d3d52.png)

**Comment by ams-tschoening** [comment]
The point is: What does that error with template tell you, what the standard 404 of the browser doesn't? What exactly is "NOT FOUND"? In my opinion, answering that question only is worth individual templates, otherwise I don't see too much benefit. Additionally, one needs to make sure that no controls are available in the template for which no data is available. Look at the parts `Rev ?rev?` in your screenshots.

So if the error message contains that a given repo name is not found or some requested path is not found or alike, templates make sense, otherwise they don't too much. So what needs to be done is introducing one template telling about those concrete errors only, designed to not contain controls not available when those errors occur etc. The concrete error messages need to be added to all/many supported languages etc. I'm just questioning if this is worth it, especially when looking at how repos can be missing at all? Do those errors happen often at all? I doubt it.

Besides that, using one and the same concrete template to only show errors perfectly well fits into the suggestion to change `renderTemplateNoRepo` to not use a template name anymore. The general error-template would be the same for all templates, only the content of the error message would change.

**Comment by k10blogger** [comment]
Yeah the error message i wrote was meaningless just a placeholder. From what i can see in the code There already exists `$lang["NOREP"]`
https://github.com/websvnphp/websvn/blob/9e265370fdde3dc2809b125c271bc59f3c9e6318/languages/english.php#L34

As for the use case, i think it is more to do with bookmarking. Take an example snapshot from the JAZZ RTC:
![image](https://user-images.githubusercontent.com/4973182/95380692-ba986200-0904-11eb-9fd6-4471148f9d2c.png)

These refer to repositories that redirects to the websvn for viewing. In scenario the repository is removed from the WebSvn over a period of time but this history remains so NoRepo comes into picture.

Another use case is the change in name of repository rare but still happens. So the URL still refers to websvn listingphp page, which will have nothing to show. 

The most common use could also be the sharing of the diff url for a repository that is not accessible if on remote server.  Here i mean the websvn server is responding but the remote server where subversion is hosted is not responding so still it would be no repo error. Other could be bad URL provided.
