### ISSUE TITLE
No downloading of folders

### ISSUE THREAD

**Issue by vince6e74** [websvnphp/websvn#136]
It is not possible to download a folder e.g. as a ZIP file

**Comment by michael-o** [comment]
?? The Download button works flawlessly for me. Please clarify!

**Comment by k10blogger** [comment]
Closing as download works. Please elaborate if need to be reopen.

**Comment by oobi** [comment]
I wasn't able to make this work. I get a 500 error when trying to download multiple files as zip. 

I tried explicitly setting the gzip command path set to the bin folder (i.e. "$> which gzip")
`$config->setGZipPath('/usr/bin/'); `

The error log isn't telling me anything beyond "there was an error". 

`GET /dl.php?repname=xxx&path=/trunk/&isdir=1& HTTP/1.1`

I tracked it down to this include in dl.php

`if (!defined('USE_AUTOLOADER')) {
	@include_once 'Archive/Tar.php';
}`

That path (Archive/Tar.php) does not exist in the build.

**Comment by michael-o** [comment]
You are confusing. What do you actually want ZIP files or tarball? You contradict yourself.

**Comment by ams-tschoening** [comment]
> if (!defined('USE_AUTOLOADER')) { @include_once 'Archive/Tar.php'; }

Your setup is incomplete: You either need to use composer to properly install all dependencies or install required dependencies manually using PEAR, like in the following docs:

https://websvnphp.github.io/docs/install.html#installation

TAR is simply always required currently, if used or not.

**Comment by oobi** [comment]
All good - I don't need/want TAR - just zip. I had assumed that either was optional - thanks @ams-tschoening for the clarification.

Commenting out the line I referenced (including Archive/Tar.php) worked fine for my purposes. I popped that up to help anyone else who hit the same problem. Sorry if that was confusing.

Perhaps it might be good to add a file_exists check for Tar.php? That would stop it freaking out if that particular package isn't installed. 

For the record I did install all the pear dependencies:

`$> pear list

Archive_Tar      1.3.11  stable
Console_Getopt   1.3.1   stable
PEAR             1.9.4   stable
Structures_Graph 1.0.4   stable
Text_Diff        1.2.2   stable
XML_Util         1.2.1   stable`

For curiosity sake, I tried doing it via composer just to see what it brings down - Archive/Tar.php still isn't available on the path it references. I'm not clear on where/how Archive/Tar.php should come from.

**Comment by michael-o** [comment]
If tar archive is only used for download, I would really consider to make it optional conditionally on the config object. Otherwise it does not make sense to require it unconditionally.

**Comment by ams-tschoening** [comment]
> For curiosity sake, I tried doing it via composer just to see what it brings down - Archive/Tar.php still isn't available on the path it references.

Your referenced path is ONLY for PEAR, NOT for Composer, that handles things internally. I'm not too familiar with how Composer manages dependencies, but simply search you whole WebSVN directory and you most likely find `Tar.php` somewhere, not only in the path you expect it. But again, that would be totally fine.

> I'm not clear on where/how Archive/Tar.php should come from.

When NOT using Composer, your referenced path is correct, because it it assumed relative to a concept called [include_path](https://www.php.net/manual/en/ini.core.php#ini.include-path) and your PEAR directories should be part of that. If you installed TAR using Pear and it's still not found, those include paths are most likely incorrect in your web server/PHP setup. You can check those things using [phpinfo](https://www.php.net/manual/en/function.phpinfo.php). This outputs e.g. the following for me:


include_path | C:\Users\httpd\AppData\Roaming\PHP\7.4&nbsp;TS\pear | C:\Users\httpd\AppData\Roaming\PHP\7.4&nbsp;TS\pear
-- | -- | --


> If tar archive is only used for download, I would really consider to make it optional conditionally on the config object. Otherwise it does not make sense to require it unconditionally.

Sounds like a good topic for another issue/discussion. Keep in mind, though, that we don't have any good dependency/pre-loading besides Composer and including some dependencies is already cluttered above the code base. If PEAR is simply wrongly setup in this case, might not be worth a code change at all as well.
