### ISSUE TITLE
Search does not function.

### ISSUE THREAD

**Issue by Douma33** [websvnphp/websvn#137]
Using:
-  WebSVN 2.6.0
- Apache Subversion 1.9.7 both on a Synology NAS (intel based)
- PHP 7.0
- Apache 2.4.43

Problem:
After installing on the NAS and registering the SVN repository (no user name, no password) then websvn functions as expected. Showing the versions, data etc. When trying to find a file through the search bar, an error arrises:

No output on STDOUT.Subcommand 'list' doesn't accept option '--search ARG'<br />

Basically I have done this research:
- through terminal I have tried the command :  svn --non-interactive --config-dir /tmp/websvn list -R --search "test" --xml -r 4 'svn://192.168.1.30/Exakt/@' It gave the same result.
- When looking into the svn help, it appears that the svn installed does not support the --search option on the list command.
- Checking the internet, I see usually the option of using a list command without search and pipe it to grep to do the searching. I do understand it would be very difficult to get the results in xml style by that method. 

So my conclusion is: 
Either I am using a strange SVN version (though I also cannot find this --searh option on the ApacheSVN documentation) or it has been tested on an other SVN engine.

Is there a workaround?

**Comment by michael-o** [comment]
Upgrade Subversion: http://subversion.apache.org/docs/release-notes/1.10.html#ls-search

**Comment by ams-tschoening** [comment]
Guten Tag Douma33,
am Montag, 1. Februar 2021 um 18:16 schrieben Sie:

> Is there a workaround?

In theory you could create a custom SVN wrapper shell script checking
for the command line incompatible with your version of SVN and
implement the missing functionality using GREP or alike on your own.
Have a look at "setSVNCommandPath" in the config, you can change that
to a directory containing your own wrapper. I've done that in the past
because of encoding issues in my shell/environment, though this was
FAR easier than your problem.

You should try to get a more recent SVN instead, as has been
suggested.

Mit freundlichen Grüßen

Thorsten Schöning

-- 
Thorsten Schöning
AM-SoFT IT-Service - Bitstore Hameln GmbH i.G. ist ein Mitglied der Bitstore Gruppe - Ihr Full-Service-Dienstleister für IT und TK

E-Mail: Thorsten.Schoening@AM-SoFT.de
Web:    http://www.AM-SoFT.de/

Telefon: 05151-  9468- 0
Telefon: 05151-  9468-55
Fax:     05151-  9468-88
Mobil:    0178-8 9468-04

AM-SoFT IT-Service - Bitstore Hameln GmbH i.G., Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB neu - Geschäftsführer: Janine Galonska


Für Rückfragen stehe ich Ihnen sehr gerne zur Verfügung.

Mit freundlichen Grüßen

Thorsten Schöning


Tel: 05151 9468 0
Fax: 05151 9468 88
Mobil: 
Webseite: https://www.am-soft.de 

AM-Soft IT-Service - Bitstore Hameln GmbH i.G. ist ein Mitglied der Bitstore Gruppe - Ihr Full-Service-Dienstleister für IT und TK

AM-Soft IT-Service - Bitstore Hameln GmbH i.G.
Brandenburger Str. 7c
31789 Hameln
Tel: 05151 9468 0

Bitstore IT-Consulting GmbH
Zentrale - Berlin Lichtenberg
Frankfurter Allee 285
10317 Berlin
Tel: 030 453 087 80

CBS IT-Service - Bitstore Kaulsdorf UG
Tel: 030 453 087 880 1

Büro Dallgow-Döberitz
Tel: 03322 507 020

Büro Kloster Lehnin
Tel: 033207 566 530

PCE IT-Service - Bitstore Darmstadt UG
Darmstadt
Tel: 06151 392 973 0

Büro Neuruppin
Tel: 033932 606 090

ACI EDV Systemhaus Dresden GmbH
Dresden
Tel: 0351 254 410

Das Systemhaus - Bitstore Magdeburg GmbH
Magdeburg
Tel: 0391 636 651 0

Allerdata.IT - Bitstore Wittenberg GmbH
Wittenberg
Tel: 03491 876 735 7

Büro Liebenwalde
Tel: 033054 810 00

HSA - das Büro - Bitstore Altenburg UG
Altenburg
Tel: 0344 784 390 97

Bitstore IT – Consulting GmbH
NL Piesteritz 
Piesteritz
Tel: 03491 644 868 6

Solltec IT-Services - Bitstore Braunschweig UG
Braunschweig
Tel: 0531 206 068 0

MF Computer Service - Bitstore Gütersloh GmbH
Gütersloh
Tel: 05245 920 809 3

Firmensitz: MF Computer Service - Bitstore Gütersloh GmbH, Gildestraße 25, 33442 Herzebrock-Clarholz
Geschäftsführer Janine Galonska
