### ISSUE TITLE
$tempDir is not removed if connection is closed during processing some download.

### ISSUE THREAD

**Issue by DimkaM** [websvnphp/websvn#141]
Dir TempDir is not removed if the connection is aborted. Search robots generate temporary files tens of gigabytes in two days.

Need fix dl.php:

          $tempDir = tempnamWithCheck($config->getTempDir(), 'websvn');
          @unlink($tempDir);
          mkdir($tempDir);
       ++ register_shutdown_function(removeDirectory,$tempDir);

**Comment by michael-o** [comment]
This makes sense...

**Comment by ams-tschoening** [comment]
There are multiple calls to `tempnamWithCheck` in different files and all of those request could be aborted at any time. So doesn't the same problem apply to all of those places creating temporary directories? Might only be less severe in others because of less amounts of data created. Though, as `tempnamWithCheck` is a custom function anyway already, how about adding the call to `register_shutdown_function` there directly? Optionally with an additional argument making that call or not with making it by default. If some temp dirs need to survive request scope, callers could achieve that, otherwise they are always cleaned up.

Thoughts?

**Comment by k10blogger** [comment]
Okay `register_shutdown_function` will stay in all `tempnameWithCheck` call but only be invoked in the `dl.php`. Correct??

**Comment by DimkaM** [comment]
> 
> 
> Okay `register_shutdown_function` will stay in all `tempnameWithCheck` call but only be invoked in the `dl.php`. Correct??

I fixed it with "register_shutdown_function (removeDirectory, $tempDir);". The month works without errors. The temporary directory does not grow.

**Comment by ams-tschoening** [comment]
I've created a PR with the necessary changes, e.g. because `removeDirectories` wasn't available and minor stuff like that. Things worked for me in a short test on UB 18.04, but simply have a look yourself.
