### ISSUE TITLE
Customization of index.tmpl in calm and Elegant

### ISSUE THREAD

**Issue by michael-o** [websvnphp/websvn#44]
Both templates provide the option to customize a specific text block. While the idea is nice, it poses a problem when WebSVN is managed by a ports/package manager. If an admin changes that text block, this is overriden as soon as an update happens by your OS.

In my case, I have changed `calm/index.tmpl` for a factory related stuff I work, but FreeBSD daily root reports nag me that the checksum of the file has been changed.

How can we solve this better? Is has to be a per-template config option because the structure is different.
E.g., `$config->setTemplateAboutText($templateName, $textBlock)`?

**Comment by tschoening** [comment]
You are talking about the part `<div id="info">` at the top of the file, correct? I had a look at the template docs and the associated code and found `websvn-include` the following, which doesn't seem to be documented:

	function parseCommand($line, $vars, $handle) {
		global $ignore, $ignorestack, $ignorelevel, $config, $listing, $vars;

		// process content of included file
		if (strncmp(trim($line), '[websvn-include:', 16) == 0) {
			if (!$ignore) {
				$line = trim($line);
				$file = substr($line, 16, -1);
				parseTemplate($file);
			}
			return true;
		}

This is how templates are passed:

	function parseTemplate($file) {
		global $ignore, $rep, $config, $vars, $listing;

		$template = (($rep) ? $rep->getTemplatePath() : $config->getTemplatePath()).$file;
		if (!is_file($template)) {
			print 'No template file found ('.$template.')';
			exit;
		}

		$handle = fopen($template, 'r');

So this looks to me like the templates can include arbitrary other templates, but I didn't find an example yet. This doesn't seem to be used. So I suggest to remove the currently available example HTML and replace it with some special `include` instruction. The included file is NOT available by default, but can be created locally like the config file and contain arbitrary HTML because of `parseTemplate` I guess.

The only problem is that `parseTemplate` errors out on non existing files currently. Let's simply add some additional optional boolean arg to not error out for some missing files and return an empty string instead. That boolean arg is `false` by default to keep backwards compatibility and given with a `true` value in the call for `websvn-include`. In the end, WebSVN tries to always includes a special file and simply doesn't if it's missing.

    [websvn-include:common_visitor_greeting.tmpl]

vs.

    [websvn-include:common_repo_description.tmpl]

vs.

    [websvn-include:all_tmpls_index_info.tmpl]

vs. something completely different or a combination of parts of all of those. :-)

	function parseTemplate($file, $mustBeAvailable = true) {

vs. 

	function parseTemplate($file, $isOptional = false) {

vs. ...

**Comment by michael-o** [comment]
Your assumptions are correct, thank for the analysis. I'd go the easy way. Move the current snippets and use `[websvn-include:...]` which I've tried locally and they are fine. No PHP code changes necessary. The bonus is that a package maintainer can mark the `user_greeting.tmpl` as a sample not prone to changes.

WDYT?

**Comment by tschoening** [comment]
If an existing example file works for you, I'm fine with this.

**Comment by michael-o** [comment]
Yep, it does for me. Though, will affect users who have changed those snippets. Unavoidable, if you want to do any changes.
