### ISSUE TITLE
Consider rebasing master

### ISSUE THREAD

**Issue by michael-o** [websvnphp/websvn#50]
Currently, master is polluted with merge commits (`--no-ff`) which makes it really hard to read. I propose to rebase master to get a clean, readable history and avoid any merge from within GitHub which produces a merge commit.

I consider a merge commit justified if you have tens or hundreds commits on your branch and you need additional comments on, but not in our case for one or two commits per branch.

Here is an example, cleaned up master: https://github.com/michael-o/websvn/commits/rebased_master

Given that we have very little clones, this can be justified to be done for our users.

**Comment by joubertredrat** [comment]
For me without a problem.

**Comment by michael-o** [comment]
@tschoening What do you say?

**Comment by tschoening** [comment]
Guten Tag Michael Osipov,
am Donnerstag, 1. März 2018 um 10:42 schrieben Sie:

> @tschoeningWhat do you say?

I'm not using Git that often, but I tend to totally disagree in that
very common rebase-discussion. Especially because I'm using GUI-Tools
like TortoiseGit anyway, which seems to even be possible to remove
merge commits from the view.

Looking at your history and if I'm not missing something, all info
about which PRs have been merged is gone. In my opinion the association
of commits and PRs using a merge commit is a valuable piece of
information in case of future problems or to simply read about things
that have been discussed in the past.

Additionally, from my understanding merge commits are the default in
GitHub anyway, so it's very likely that they will be reintroduced in
future even by accident.

So in my oponion no, rebasing is not worth it breaking existing forks
and loosing valuable information and no, I don't think we should avoid
merge commits at all.

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow

**Comment by michael-o** [comment]
Well, you always have to use `--no-merges`, this is cumbersome for most and cannot be provided in the GitHub log view.. As for the loss of information: You can always retain the context by referencing the issue no in the commit itself. This is common usage on GitHub. Everything is cross linked on GitHub automatically. Especially because you work via milestones and PRs assinged to it, you will have the context to. In a clean flow, me and others using on GitHub you likely never lose context. We have very little forks on GitHub, for the clones, this is a one-time event.

**Comment by mojca** [comment]
If you disable merge commits on pull requests, the pull requests will automatically be rebased when you click the button. Then you only need to discipline the very small number of people with direct commit access to avoid doing merges (local git checkout can also be configured to always apply `--rebase` on `git pull`).

If you rebase, you will only lose references to all the pull requests done in the past, but if you rebasing and thus modifying history anyway, you can just as well edit all the old commit messages and add explicit links to PRs or issues. Just run
```
git rebase -i HEAD~100
```
and then edit commit messages. Since you only have 36 pull requests closed, this is totally doable. The five people who forked the project would probably survive.

Anyway, even if you don't modify the past history, you can still disable merging of pull request and only allow the "rebase and merge" button.

**Comment by michael-o** [comment]
> If you disable merge commits on pull requests, the pull requests will automatically be rebased when you click the button. Then you only need to discipline the very small number of people with direct commit access to avoid doing merges (local git checkout can also be configured to always apply --rebase on git pull).

Correct, I see no huge problem here.

> If you rebase, you will only lose references to all the pull requests done in the past, but if you rebasing and thus modifying history anyway, you can just as well edit all the old commit messages and add explicit links to PRs or issues. 

That is why I don't like to merge at GitHub at all. Locally, I can amend the merged commit and add the PR#. Problem solved.

**Comment by michael-o** [comment]
So folks, can we agree to rebase/rewrite and in future to merge locally and amend with PR to retain the desired information?

**Comment by tschoening** [comment]
Not for me, I don't follow your arguments and other projects do merge commits as well. There's no point in forcing me to do locally and manually what GitHub already does in the web easier and automatically.

**Comment by mojca** [comment]
You don't need to switch to command line to achieve that.

If you go to Settings -> Options -> Merge button and uncheck "Allow merge commits" (and maybe "Allow squash merging", depending on local preference), the changes will always be rebased when you click the button in the interface.

**Comment by michael-o** [comment]
@mojca I don't have that permission on the repo. Even if, I would still like to have a concensus decision.

**Comment by michael-o** [comment]
@tschoening Why not switch GitHub what @mojca is referring to? Is that acceptable for you?

**Comment by tschoening** [comment]
No, my current opinion is that I prefer merge-commits, because I think they provide valuable information, especially how they are handled by GitHub with all the commit text created by default to reference PRs and such.

If that setting is changed in GitHub, those commit texts are missing by default. So either we loose them or one is forced to merge locally and add those references manually. And no, not all PRs will have corresponding issues, no, not all contributors of PRs will mention issues and no, I don't want to amend multiple commit messages of one PR to mention the PR or issue all those commits belong to. That is exactly what branches and merge commits are doing automatically.

I totally understand that you disagree, it's a matter of taste for some, pretty much like code style and all that stuff, but your client should be capable of ignoring merge commits already. So why force all people to follow your workflow, change default behaviour of GitHub and maybe even loose valuable information which can not be restored etc., if you easily are able to get what you want by the help of your client?

I won't even force you to merge-commit. While I do prefer those for now, opinions might change of course, I can live with not getting them. The point is that you try to force everyone else not using them. Of course it's bad for your point of view that default settings are the way they are in Git and GitHub, but that wasn't my decision, I only benefit of it. ;-)

So, to come to an end, we simply do not agree on this topic. So it's up to other project members to follow either your arguments or mine or don't care or whatever.

**Comment by michael-o** [comment]
@tschoening If I would force, I wouldn't have this discussion at all. It would be plain simple.

**Comment by michael-o** [comment]
Since we cannot agree, I'll drop this one.
