### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by joubertredrat** [websvnphp/websvn#7]
I used this project years ago, but currently this project is still used.

On oficial WebSVN mailinglist, the creator of project open a thread to talk about a new maintainer. Today I use git for my projects, but I'm a PHP developer and I know how to SVN works, then I can help and continue project without problems.

What you think @dirk-thomas? I want to add you on @websvnphp organization too, because if you not created this project, a lot of customers would have a option to see your SVN repositories data.

Reference:
http://websvn.tigris.org/ds/viewMessage.do?dsForumId=1547&dsMessageId=3172668

**Comment by dirk-thomas** [comment]
Thank you for referencing me here. The Tigris mailing list is receiving so much spam that I simply don't see those messages - they are just being buried in the spam folder.

You don't have to add me to this organization. I am not using SVN anymore and won't be able to contribute to the project.

Imo it would be "nicer" to continue the project on Tigris (or more specifically in a SVN repository). For example http://demo.websvn.info / http://trunk.websvn.info provide a nice test to try WebSVN on its own repository. If you would like to I would be more than happy to add you to the Tigris project.

If you prefer to keep the fork in GitHub that is of course fine too. If you want me to add any reference to it from the Tigris page or http://www.websvn.info please let me know and I am happy to do so.

**Comment by joubertredrat** [comment]
Hi @dirk-thomas 

Thanks for your response. I'm not using SVN too, but you created this project, I think that you albe to be in organization as contributor, you created the project and maintained few years ago and still keeps the site active, even if the project is stopped. I really will like that you enter on organization :)

About the location of project, is really ironic to use git to maintain the project, but I think that GitHub is excellent for open source and collaborative projects. For demo is possible to use various option as below:

Official subversion repo that contains subversion :joy: 
https://svn.apache.org/repos/asf/subversion/

Wordpress repository
https://develop.svn.wordpress.org/

Or we can use this git repo, why not?
```bash
dev@ci08:~
➤ svn info https://github.com/websvnphp/websvn/
Path: websvn
URL: https://github.com/websvnphp/websvn
Relative URL: ^/
Repository Root: https://github.com/websvnphp/websvn
Repository UUID: bf94aba7-0c54-3998-e986-ce57b7db7bff
Revision: 1239
Node Kind: directory
Last Changed Author: joubert.redrat
Last Changed Rev: 1239
Last Changed Date: 2017-08-29 10:21:59 -0300 (Ter, 29 Ago 2017)
```

**Comment by dirk-thomas** [comment]
> I'm not using SVN too, but you created this project, I think that you able to be in organization as contributor, you created the project and maintained few years ago and still keeps the site active, even if the project is stopped. I really will like that you enter on organization :)

I actually didn't create WebSVN. Tim Armes created the project long time before I took over as a maintainer.

I will simply not have the time to read any issues / PR or contribute in any other way to the future project. So adding me to the org unit doesn't make much sense. The existing site hasn't been touched for many years - it just happens to still work :wink:

> About the location of project, is really ironic to use git to maintain the project, but I think that GitHub is excellent for open source and collaborative projects. For demo is possible to use various option as below:

I think you kind of need a repository you have control over yourself. It is often handy to have a set of commits replicating a specific case on a branch and being able to view it through WebSVN for debugging as well as validation. If the SVN access of the GitHub repo would work that sounds like a good choice to me. But ultimately it will be your call...

**Comment by tschoening** [comment]
My 2 cents: Keep the project on GitHub and referring to this as a somewhat new home or such by @dirk-thomas would be great. Especially projects with little activity benefit from GitHub because it's pretty easy for everyone to fork and provide even small patches using PRs. That's often enough to keep a project in a running state. If I didn't find the fork of @joubertredrat, I would have created my own.

Regarding some example SVN repo, while the GitHub SVN-Bridge works mostly, I use it somewhat heavily, you won't be able to test/demonstrate things like access files and such. But for only browsing an existing public repo it should be enough.

**Comment by tschoening** [comment]
Additionally I would like to mention that I'm pretty sure not to have much/any time to work on the project myself as well. Only as needed to keep it running for as long as I keep using it. But again, I think that's one of the strengths of GitHub, just let people contribute whatever they are willing to provide.

**Comment by dirk-thomas** [comment]
Until now the website www.websvn.info was hosted on my webserver using a PHP-based CMS. I just converted the webpage into static html files hosted using GitHub pages (from [this](https://github.com/dirk-thomas/websvn.github.io) repo) since I don't want to continue hosting the webpage on my webserver anymore. With that move the subdomains demo.websvn.info and trunk.websvn.info won't be available anymore to show a "live" WebSVN instance listing its own SVN repo. The git repo can stay were it is or can be moved to this org unit. I would leave that up to you.

Btw. I found another WebSVN repo on GitHub: https://github.com/crazy-max/websvn Maybe it would be a good idea to contact the owner of that repo with the goal of consolidating the repos / effort.

**Comment by tschoening** [comment]
Thanks for you efforts and in my opinion it would be a good idea if the pages repo gets moved to the organisation as well. This way everything is one place and you don't need to deal with PRs or whatever. What's the exact process to follow, do you need to init a transfer or shall I import your repo into the org or ...? Don't have much experience on this.

Additionally, I've written @crazy-max an email to inform him about this organization.

**Comment by dirk-thomas** [comment]
I transferred the repo to this org unit (see https://github.com/websvnphp/websvn.github.io). I would be good if you could give me admin access to the repo though since it uses my domain atm and I can't reach the repo settings after the transfer.

**Comment by joubertredrat** [comment]
Hi @dirk-thomas, I changed your role in org as owner for now. Thanks

**Comment by dirk-thomas** [comment]
> I changed your role in org as owner for now.

The repo would have been sufficient. But thanks anyway.

**Comment by crazy-max** [comment]
Hi,

I originally made a mirror of this repository for the [Neard](http://neard.io/) project because it uses it as a module.
This repo is sync every 15minutes with the SVN from http://websvn.tigris.org/svn/websvn/trunk/.
I you want, i can transfer this repo in this organization and keep the sync.

**Comment by tschoening** [comment]
What's the benefit of transferring your entire repo? It seems to me the better approach would be you provide PRs for the things you have changed. I only recognized `README.md` for now, but you know better about your changes. From my understanding there won't be any commits to the SVN repo anymore, so I don't think the sync is needed.

After your PRs you could consider integrating a fork of the repo of this organization into your project. It should contain at least one bugfix you might not have currently:

https://github.com/websvnphp/websvn/pull/4

**Comment by crazy-max** [comment]
Ok no problem, but i have authors linked to their Github account as you can see :

https://github.com/crazy-max/websvn/commits/master :

![image](https://user-images.githubusercontent.com/1951866/32665160-af962e08-c633-11e7-90b4-747c28b16c62.png)

https://github.com/websvnphp/websvn/commits/master :

![image](https://user-images.githubusercontent.com/1951866/32665213-d74eaf06-c633-11e7-864a-5c74e047384d.png)

But this is not a real issue here ;)

**Comment by tschoening** [comment]
And what needs to be done to link authors to their accounts like you did? Is that only possible during repo creation/commit sync? Looks good of course, but not sure if it's worth the work to switch the repos, re-apply my former PRs and such.

**Comment by crazy-max** [comment]
I think i can make a PR and rewrite the history to linked commits to Github authors.
I'll keep you in touch.

**Comment by tschoening** [comment]
How does rewriting the repo effects current forks? I have existing additional branches and such.

**Comment by crazy-max** [comment]
Indeed, a PR is not possible if the history is rewritten (sse my fork https://github.com/crazy-max/websvn-1).
If you give me write access to the repository i can rewrite and push the history to all branches / tags.

**Comment by tschoening** [comment]
As we have only two forks currently, I guess it's now or never? I don't have any work in progress, only private branches based on master which I could easily re-create if necessary.

**Comment by crazy-max** [comment]
@tschoening Ok nice then! Can you give me write access to push to this repo ?

**Comment by tschoening** [comment]
Don't think so, I'm a member like you are. I've created two teams, @websvnphp/core-devs and @websvnphp/website-devs, and suggest @joubertredrat manages permissions to repos based on those teams. Or give me permissions to manage those myself...

**Comment by joubertredrat** [comment]
Hi @tschoening, I created permissions as you requested. Thanks

**Comment by crazy-max** [comment]
@joubertredrat Oh! Just when I published a tool to rewrite the author history 😆 [git-rewrite-author](https://github.com/crazy-max/git-rewrite-author).

**Comment by dirk-thomas** [comment]
As mentioned [above](https://github.com/websvnphp/websvn/issues/7#issuecomment-343035725) I have recently already removed the dynamic features of the website since I am migrating away from my previous hosting provider. The only thing left is the domain `websvn.info` which is currently registered until 2018-04-02. Is anyone interested in taking over the domain since I am not sure if I want to renew it when the time comes?

**Comment by crazy-max** [comment]
Ok i have just pushed the rewritten history.

**Comment by joubertredrat** [comment]
@dirk-thomas I think that is good idea to let domain expire and redirect to websvn.github.io before expire. What yout think?

**Comment by crazy-max** [comment]
@joubertredrat We do not own `websvn.github.io`. [This user](https://github.com/websvn) is already taken.
We can only use `websvnphp.github.io`. Maybe we can report this user to Github staff ?

**Comment by joubertredrat** [comment]
@crazy-max We can try to report, but I think that Github will talk that is valid user. We can use `websvnphp.github.io` instead.

**Comment by crazy-max** [comment]
I have sent an email to Github Staff and they are going to contact the user asking them to rename their account. Fingers crossed ;)

**Comment by dirk-thomas** [comment]
I have renamed the repo containing the website to [websvnphp.github.io](https://github.com/websvnphp/websvnphp.github.io) in order to match the name of the current org unit.

I have also update the html to:

* work with [relative links](https://github.com/websvnphp/websvnphp.github.io/commit/247e985a83cee085f4ba233d877e9384c2caa5b9)
* replace the [websvn.info domain](https://github.com/websvnphp/websvnphp.github.io/commit/a20a6453e93d6e22f7507d3e0e5720f5c5ca39fc)
* remove the [hosting note](https://github.com/websvnphp/websvnphp.github.io/commit/f4fdfd118980fac9c71b1b6bfcf5a7ff1382ae69) from the footer
* move the names of the [previous maintainers](https://github.com/websvnphp/websvnphp.github.io/commit/1f083f413e2911bcba095313c924cc15659cbf34)

The previous domain `websvn.info` is now redirecting to the new location (including any paths behind the domain): https://websvnphp.github.io/websvnphp.github.io/ The domain `websvn.info` will expire in April 2018 which should be long enough for search engines to pick up the new location.

**Comment by crazy-max** [comment]
@dirk-thomas Why https://websvnphp.github.io/websvnphp.github.io/ ?
https://websvnphp.github.io/ works here.

**Comment by dirk-thomas** [comment]
Hm, when I tried it the short version didn't work yet. Not sure why though. Since it works now I switched to the short URL (https://github.com/websvnphp/websvnphp.github.io/commit/d2aa7b423de864bc429704f4414b0eb7d91aefba).

**Comment by crazy-max** [comment]
@dirk-thomas DNS propagation i think because `CNAME` file was not refreshed maybe.
Btw, I tried to contact @websvn to ask him if he could change his username (issue websvn/doc#1) but no response yet.

**Comment by michael-o** [comment]
Hi folks, I have personally [forked WebSVN](https://sourceforge.net/u/michael-o/svn-enterprise-auth/HEAD/tree/websvn/) some time ago for our work Subversion server. Fixed a lot of personal issues, removed the entire lib stuff, used `svnauth(1)` and other small stuff. See my [changes](https://sourceforge.net/u/michael-o/svn-enterprise-auth/HEAD/tree/websvn/tags/2.4.0/changes.txt).

I'd like to reconcile the stuff and have it maintained once in a while. No huge changes, since I don't have the time for this. Especially I am interested in bringing the FreeBSD port on par with my/your changes w/o maintaining my own port.

Tell me what you think?!

**Comment by tschoening** [comment]
So in the end you want to make your 2.4.0 with all changes the new master of this repo or only take the changes that makes sense/we agree on?

In my opinion your changes really need to be broken down into more handy pieces and made available as PRs which can optionally be reviewed and discussed. Maybe we should open a new issue to coordinate this process? Afterwards one could create some branches and apply the diffs of your SVN history as necessary. We should not apply all changes in one commit, because they seem to contain some changes breaking current installations.

I had a quick look and those breaking changes are renaming of `wsvn`, usage of `[svnauthz](https://helpmanual.io/help/svnauthz/)` which might not be available, removing of basic auth and some Windows-compatibility problems by setting `LANG=` for some command line invocations. Some of this can be worked around, e.g. using symlinks for `wsvn`, but some might be discussed if it should really be applied and if so, this should made as easy as possible to debug in case of problems.

I might be able to help on breaking down your changes into PRs, especially because I'm covered by your breaking changes `wsvn`, the `BlueGray`-theme and basic auth. :-/

**Comment by crazy-max** [comment]
@michael-o I agree with @tschoening. PR are welcomed in this kind of process, specially with a desynchronized history.

**Comment by michael-o** [comment]
@tschoening

> So in the end you want to make your 2.4.0 with all changes the new master of this repo or only take the changes that makes sense/we agree on?

Ideally all, but we need to check every single one.

> In my opinion your changes really need to be broken down into more handy pieces and made available as PRs which can optionally be reviewed and discussed. Maybe we should open a new issue to coordinate this process? Afterwards one could create some branches and apply the diffs of your SVN history as necessary. We should not apply all changes in one commit, because they seem to contain some changes breaking current installations.

Never expected to merge all in one commit, that would be insane. Piece by piece with distinct PRs.

> I had a quick look and those breaking changes are renaming of wsvn, usage of [svnauthz](https://helpmanual.io/help/svnauthz/) which might not be available, removing of basic auth and some Windows-compatibility problems by setting LANG= for some command line invocations. Some of this can be worked around, e.g. using symlinks for wsvn, but some might be discussed if it should really be applied and if so, this should made as easy as possible to debug in case of problems.

* Those things you have mentioned, renaming wsvn to browse felt more natural and makes more sense with `/repos/websvn/browse` than `/repos/websvn/wsvn`. I didn't want to fiddle with mod_urlrewrite.
* `svnauthnz(1)` has been around for years. The manual parsing of the authz file was broken, it did not the same what `mod_authz_svn` did.
* I removed Basic auth because this is really a server thing to do, Apache Web Server or nginx. Moreover, I am using `mod_auth_gssapi` at work.
* `LANG` of source needs to be investigated, but is crucial as soon as you have non-ASCII output which I have. Since I am hosting on FreeBSD, I didn't much care about Windows ;-)

> I might be able to help on breaking down your changes into PRs, especially because I'm covered by your breaking changes wsvn, the BlueGray-theme and basic auth. :-/

As for the themes. I removed then, but Calm because I made some fixes to and was simply too lazy to merge it to the others.


My goal is basically to give the stuff back and ideally remove my fork where we all will be happy.

Shall I create a new ticket with my `changes.txt` for further discussion?

**Comment by tschoening** [comment]
Guten Tag Michael Osipov,
am Mittwoch, 7. Februar 2018 um 09:34 schrieben Sie:

> `LANG` of source needs to be investigated, but is crucial as soon as
> you have non-ASCII output which I have.

I worked around that problem by creating a wrapper for the svn binary
setting LANG in there:

> #!/bin/sh
>
> export LC_CTYPE=de_DE.UTF-8
> svn $*

I prefer something like that over changing every command line
invokation in the source and it's at least somewhat compatible with
Windows because everyone could create such a wrapper as needed and the
project provides a default one or something like that.

> Shall I create a new ticket with my changes.txt for further discussion?

Sounds good and we can go even further and directly create PRs for all
of your changes linked to that issue. I expect most of them will be
included at least somehow anyway and everyone is free to merge them
ones publicly available. You won't lose any work and still can delete
your fork.

I suggest grouping PRs along the following keywords:

> CVE_fixes
> rm_legacy_themes
> rm_basic_auth
> code_style with ndash, line endings, legacy PHP(?) and stuff
> geshi_compat
> svnauthz
> renames with wsvn, /repos/websvn, /tmp/websvn, useAccesFile
> fix_dir_listing incl. datetime...
> UTF-8_compat vs. locale_compat vs. ...

Archive_Tar and Text_Diff are removed already and this seems to follow
your changes and commits mostly. That was just my impression from
looking at your changes, feel free to decide otherwise or more fine
grained or whatever of course.

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow

**Comment by michael-o** [comment]
The wrapper is quite ugly because you need to maintain locale twice, in config.php as well as in all of your wrappers. Isn't there a better way to do this?

I am quite happy with the rest. Will likely start on Friday with PRs.

**Comment by tschoening** [comment]
Guten Tag Michael Osipov,
am Mittwoch, 7. Februar 2018 um 13:49 schrieben Sie:

> The wrapper is quite ugly because you need to maintain locale twice,
> in config.php as well as in all of your wrappers. Isn't there a
> better way to do this, PHP is not my primary language?

Mine neither, but it breaks down to setting environment variables
which are propagated to child processes, right? Maybe a simple
"putenv" in WebSvnConfig::setLocale does it already without breaking
the executed command line itself between shells/OS.

http://php.net/manual/de/function.putenv.php#8496

> Note: I am also removed GeSHi and added external support. Fixed one
> incompat with 1.0.9.0.

I considered the removal itself "geshi_compat" as well, else the fix
wouldn't be necessary.

> I'd drop enscript because it hasn't been
> maintained for a long period of time.

Only supporting either geshi or enscript makes sense, especially as it
seems both support pretty much the same file formats. Might be worth
an individual PR instead of "geshi_compat", though? Not sure if it's
worth an individual branch or suits to geshi-related work.

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow

**Comment by joubertredrat** [comment]
@dirk-thomas @tschoening are you agree to add @michael-o to org and close this question? Because for me this is resolved.

**Comment by dirk-thomas** [comment]
I am fine with whatever you guys decide.

**Comment by tschoening** [comment]
Same here, please add him, I'll close this. @michael-o feel free to merge all approved PRs yourself afterwards.

**Comment by joubertredrat** [comment]
Done, invite sent
