### ISSUE TITLE
Characters - File not found

### ISSUE THREAD

**Issue by MosfetN** [websvnphp/websvn#73]
Hello everyone, :
Sorry if it has been answered but
I'm facing an issue with apostrophe and ampersand since version 2.4 (no issue with 2.3.3).
Even on folder name or file name, I got error "E160013: File not found"
Additionnal log : 
"Error running this command: svn --non-interactive --config-dir /tmp/websvn log --xml  --limit 2 'file:///home/repositories//IS/FR_%26amp%3B_EN@', referer: https://dev.lcl/websvn/listing.php?repname=IS" For ampersand

Is there someone who faced the same isssue?
Any clue on what has change in early versions which may cause the issue?
Many thanks for your answers

**Comment by michael-o** [comment]
Did you use `setLocale()` for Subversion to properly work?

**Comment by michael-o** [comment]
Can you also please do an `ls` on the filesystem?

**Comment by MosfetN** [comment]
Thanks a lot for your quick support.
Yes  I did uncomment UTF-8 parameter but it's not changing the behaviour.
ls on filesystem ? Sure : 
bin  boot  dev  etc  home  initrd.img  initrd.img.old  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  snap  srv  sys  tmp  usr  var  vmlinuz  vmlinuz.old
I'm running Ubuntu 18.04 with PHP 7.2

**Comment by michael-o** [comment]
That's not the output I wanted to see. Do a `ls` on the directory containing that file, also provide a `svn info` on that file.

**Comment by ams-tschoening** [comment]
The following `ls` es needed most likely, as `svn` is issued on the SVN-repo from my understanding:

    svn ls "file:///home/repositories/IS"

`FR_%26amp%3B_EN` looks like the correct URL-encoding of the file system folder name `FR_&amp;_EN` to me. But your folder most likely is named `FR_&_EN` only, correct? That would mean there's some wrong URL-encoding in WebSVN somewhere, as the correct URL for the shell would have been the following:

    file:///home/repositories//IS/FR_%26_EN@

There's a path encoded to be proper HTML for output in HTML, but afterwards directly used for building the command for the shell as well. That's wrong, the path for the shell needs to build with the original plain path without HTML-compatibility of course. The URL-encoding for the shell itself looks OK to me.

**Comment by ams-tschoening** [comment]
I can reproduce the problem, it's as expected that `&` is wrongly changed to `&amp;` somewhere:

    svn: E160013: File not found: revision 311, path '/trunk/FR_&amp;_EN.txt'

**Comment by ams-tschoening** [comment]
Found the problem:

https://github.com/websvnphp/websvn/commit/50f02cf848c5bdebb66d9b017389c9d688887d4f

That change escapes an internally used path always to be HTML-compatible, even though that path might not be used in HTML-only, like in this case. What's the correct fix? Assuming internal data is HTML-compatible or not? In my opinion, data needs to be escaped properly at output because only at output one can know how to escape. This bug is one example, HTML is simply wrong, other examples are sending paths using E-Mail or whatever. All this requires different escaping.

OTOH the change was made to fix some XSS-issue. But only because where ever that issue appeared, it wasn't properly escaped there and might have been fixed there. This change seems a bit to broad to me.

Opinions?

**Comment by ams-tschoening** [comment]
I had another look at this problem and the escaping of variables is completely broken currently: A lot of variables are escaped because they are used in HTML-templates at some point, but in most cases those variables are escaped pretty early, even thought they are used in other contexts than HTML-templates as well. In those contexts most likely plain paths are expected instead of HTML-escaped ones. This is not only happening for `listing.php`, but for `comp.php` and others as well. Have a look at the following lines in that file:

	// safe paths are a hack for fixing XSS exploit
	$vars['path1'] = escape($path1);
	$vars['safepath1'] = escape($path1);
	$vars['path2'] = escape($path2);
	$vars['safepath2'] = escape($path2);

	$vars['rev1'] = $rev1;
	$vars['rev2'] = $rev2;

	$history1 = $svnrep->getLog($path1, $rev1, $rev1, false, 1);

`path1` is escaped because it is used in some HTML-templates, but before actually rendering such a template it is used in getting log informations, which expects a plain path. And using a path like `FR_&_EN` querying the log fails of course as well.

Additionally, the concept of `safepath` has originally been introduced to be in templates only, which is sadly not the case. Sometimes `safepath` is used, sometimes not, I guess that's the reason why many individual vars are escaped. But others are not, like `rev*`, which seems to be forwarded 1:1 to templates.

There's only one fix in my opinion: Search for and remove individual calls to `escape` everywhere and remove the concept of `safepath` entirely. In `template.php`, before actually printing lines of templates, is the one and only place where the individual values of the `vars`-array should be escaped. No need to manage individual names or stuff, just escape everything and keep original data everywhere else. If other needs to escape/encode/... arise somewhere, e.g. for shell invocations, one needs to deal there with that instead of very early "just in case".

**Comment by michael-o** [comment]
@ams-tschoening, thanks for the indepth analysis. I will have at look at it this evening.

**Comment by ams-tschoening** [comment]
Have a look especially at `template.php` `parseTags`:

		// Replace variable (special token, if not exists)
		$l .= isset($vars[$matches[1]]) ? $vars[$matches[1]]: ('?'.$matches[1].'?');

That's where escaping is needed if one assumes HTML-templates mostly. Not sure how to handle `executePlainPhpTemplate`, though.

It's important to not escape `$vars` in `renderTemplate` already, because that struct is used during parsing the templates to check file types and such and these are operations during which unescaped, plain text would be assumed as well again.

**Comment by ams-tschoening** [comment]
Had another look and it seems some places really output individual lines of HTML before actually rendering main templates and therefore need to keep escaping. Would be best if that would be left to templates entirely of course. The following two functions seem to do the exact same thing as well: `xml_entities` in `util.php` vs. `escape` in `command.php`. Both seem to be used interchangeable.

**Comment by databird** [comment]
Adding, on 'includes/setup.php' :

`// To avoid a possible XSS exploit, need to clean up the passed-in path first
$path = !empty($_REQUEST['path']) ? escape($_REQUEST['path']) : null;
if ($path === null || $path === '')
	$path = '/';
$path = str_replace('&amp;','&',$path); // databird - added to solve ampersand problem on repository name
$vars['safepath'] = escape($path);`

solve our problem (repository with ampersand on name) :-)

**Comment by michael-o** [comment]
This has been fixed with 088bd1b6b5d23bbf493681c90470df82423b5e2b.
