### ISSUE TITLE
Re-instate command quoting

### ISSUE THREAD

**Issue by csalgau** [websvnphp/websvn#75]
Finally got around to trying to update WebSVN and noticed that commit https://github.com/websvnphp/websvn/commit/ec00fa73d2a3572f86b3dde3b9d6ca13e17e0774 dropped apparently redundant code and noted that since PHP 5.3 commands are automatically quoted on Windows.
This, however, is not entirely true, as the removed code is checking the PHP version only for some calls. https://github.com/php/php-src/commit/19322fc782af429938da8d3b421c0807cf1b848a from 2008 only covers `exec` and related, not `proc_open` (which, for whatever reason, does it's own thing in `/ext/standard/proc_open.c` - one of three calls to `CreateProcessW` in the entire source tree).
Please consider adding the quoting back on Windows.
Thanks.

**Comment by ams-tschoening** [comment]
Could please describe what's the actual problem you are running into? Invoking commands on paths with spaces and they fail or something else? Some example of paths, commands and errors would be helpful.

**Comment by csalgau** [comment]
That would have been the proper way of reporting the problem...
Here's a snippet of what the php log looks like.
```
[27-Mar-2019 20:39:32 UTC] Error running this command:  "D:/path/to/svn/bin\svn" --non-interactive --config-dir D:/tmp log --xml  --limit 2 "file:///d:/svn_repo/@"
[27-Mar-2019 20:39:32 UTC] The filename, directory name, or volume label syntax is incorrect.
[27-Mar-2019 20:39:32 UTC] Error running this command:  "D:/path/to/svn/bin\svn" --non-interactive --config-dir D:/tmp log --xml --quiet --limit 1 "file:///d:/svn_repo/@"
[27-Mar-2019 20:39:32 UTC] The filename, directory name, or volume label syntax is incorrect.
[27-Mar-2019 20:39:32 UTC] Error running this command:  "D:/path/to/svn/bin\svn" --non-interactive --config-dir D:/tmp log --xml --quiet --limit 1 "file:///d:/svn_repo/@"
[27-Mar-2019 20:39:32 UTC] The filename, directory name, or volume label syntax is incorrect.
[27-Mar-2019 20:39:32 UTC] Error running this command:  "D:/path/to/svn/bin\svn" --non-interactive --config-dir D:/tmp list --xml "file:///d:/svn_repo/@"
[27-Mar-2019 20:39:32 UTC] The filename, directory name, or volume label syntax is incorrect.
```
Tracing with process monitor shows proc_open effectively runs
```
cmd /c "D:/path/to/svn/bin\svn" --non-interactive --config-dir D:/tmp list --xml "file:///d:/svn_repo/@"
```
Wrapping the comand in quotes, as it was before https://github.com/websvnphp/websvn/commit/ec00fa73d2a3572f86b3dde3b9d6ca13e17e0774, fixes the issue.

**Comment by ams-tschoening** [comment]
Guten Tag Catalin Salgau,
am Donnerstag, 28. März 2019 um 13:58 schrieben Sie:

> cmd /c "D:/path/to/svn/bin\svn" --non-interactive --config-dir D:/tmp list --xml "file:///d:/svn_repo/@"

You have configured the path to your SVN-binary manually, did you?
Please provide the exact config. I geht the following command
invocation without manually configuring anything:

> cmd.exe /c svn --non-interactive --config-dir /tmp/websvn log --xml -r 255:255 "file:///C:/Users/[...]/Neuer%20Ordner@255"

I guess the first quotes around the path to the binary are added
because you have configured a path instead of relying on %PATH%.
Quoting there is the correct thing of course as the path needs to be a
path and might contain spaces.

Quoting the file-URL instead is not necessary in theory and without
that things would work as well:

> cmd.exe /c "svn" --non-interactive --config-dir /tmp/websvn log --xml -r 255:255 file:///C:/Users/[...]/Neuer%20Ordner@255

Notice the added quotes around the binary and removed ones around the
URL. With quotes in both places things would fail as well because of
the following result:

> [...]cmd.exe  5400    CreateFile      C:\Users\tschoening\svn" --non-interactive --config-dir \tmp\websvn log --xml  -r 255:255 "file:        NAME INVALID[...]
> [...]cmd.exe  5400    CreateFile      C:\Users\tschoening\svn --non-interactive --config-dir \tmp\    PATH NOT FOUND[...]

The problem is that more than one pair of quotes is used in general,
the docs of cmd.exe clearly state that the first and last quote are
removed always in such case.

So we have two choices: Either add a first and last quote back again
or not quote the URL and therefore only have one pair of quotes in
general, fulfilling the restrictions of cmd.exe. Both should be safe
in this case, but adding a first and last quote should be safer in
case individual arguments are quoted some time in future as well.

Adding quotes still works in case only one pair of quotes is used,
like in the following example: 

> cmd.exe /c "svn --non-interactive --config-dir /tmp/websvn log --xml -r 255:255 "file:///C:/Users/[...]/Neuer%20Ordner@255""

What does NOT work is if PHP adds some additional pair of quotes:

> cmd.exe /c ""svn --non-interactive --config-dir /tmp/websvn log --xml -r 255:255 "file:///C:/Users/[...]/Neuer%20Ordner@255"""

That would be the case if "popen_ex" is used from my understanding. So
we would need to check which function of PHP is used and add
additional quotes as needed? And if PHP gets changed to add quotes
automatically things fail in future.

Thoughts?

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow

**Comment by ams-tschoening** [comment]
cmd /c "D:/path/to/svn/bin\svn" --non-interactive --config-dir D:/tmp list --xml "file:///d:/svn_repo/@"

You have configured the path to your SVN-binary manually, did you?
Please provide the exact config. I geht the following command
invocation without manually configuring anything:

    cmd.exe /c svn --non-interactive --config-dir /tmp/websvn log --xml -r 255:255 "file:///C:/Users/[...]/Neuer%20Ordner@255"

I guess the first quotes around the path to the binary are added
because you have configured a path instead of relying on %PATH%.
Quoting there is the correct thing of course as the path needs to be a
path and might contain spaces.

Quoting the file-URL instead is not necessary in theory and without
that things would work as well:

    cmd.exe /c "svn" --non-interactive --config-dir /tmp/websvn log --xml -r 255:255 file:///C:/Users/[...]/Neuer%20Ordner@255

Notice the added quotes around the binary and removed ones around the
URL. With quotes in both places things would fail as well because of
the following result:

    [...]cmd.exe  5400    CreateFile      C:\Users\tschoening\svn" --non-interactive --config-dir \tmp\websvn log --xml  -r 255:255 "file:        NAME INVALID[...]
    [...]cmd.exe  5400    CreateFile      C:\Users\tschoening\svn --non-interactive --config-dir \tmp\    PATH NOT FOUND[...]

The problem is that more than one pair of quotes is used in general,
the docs of cmd.exe clearly state that the first and last quote are
removed always in such case.

So we have two choices: Either add a first and last quote back again
or not quote the URL and therefore only have one pair of quotes in
general, fulfilling the restrictions of cmd.exe. Both should be safe
in this case, but adding a first and last quote should be safer in
case individual arguments are quoted some time in future as well.

Adding quotes still works in case only one pair of quotes is used,
like in the following example: 

    cmd.exe /c "svn --non-interactive --config-dir /tmp/websvn log --xml -r 255:255 "file:///C:/Users/[...]/Neuer%20Ordner@255""

What does NOT work is if PHP adds some additional pair of quotes:

    cmd.exe /c ""svn --non-interactive --config-dir /tmp/websvn log --xml -r 255:255 "file:///C:/Users/[...]/Neuer%20Ordner@255"""

That would be the case if "popen_ex" is used from my understanding. So
we would need to check which function of PHP is used and add
additional quotes as needed? And if PHP gets changed to add quotes
automatically things fail in future.

Thoughts?

**Comment by michael-o** [comment]
Isn't there a way to avoid cmd.exe at all in PHP? This has been constant pain with Plexus Utils and Maven Shared Utils for me.

**Comment by ams-tschoening** [comment]
I am running into this problem as well:

    Fehler beim Ausführen des Befehls:  "C:/Program Files/CollabNet/Subversion Client\svnauthz" accessof --repository ActionD --path "/" "C:/Users/tschoening/Documents/Repos/Svn/AM-SoFT/BaseConf/authz"
    Der Befehl "C:/Program" ist entweder falsch geschrieben oder konnte nicht gefunden werden.

The problem this time is that the path to the authz-file really is a path instead of an URL and therefore might contain spaces. Building commands is pretty redundant in current code base, so I'm first trying to combine all calls to `proc_open` and afterwards one can decide how to handle quotes.

**Comment by ams-tschoening** [comment]
> Isn't there a way to avoid cmd.exe at all in PHP? This has been constant pain with Plexus Utils and Maven Shared Utils for me.

There might be at least for proc_open:

> bypass_shell (windows only): bypass cmd.exe shell when set to TRUE

https://php.net/manual/en/function.proc-open.php

**Comment by ams-tschoening** [comment]
I've pushed a new branch `ghi_75_proc_open_quotes`, would be great if someone could test this.

**Comment by csalgau** [comment]
Yes, setSVNCommandPath is configured.
Since you ended up with a nice solution, I won't dump pieces of my config on here.
I've pulled ghi_75_proc_open_quotes and it looks like it's working properly. (I can't say if I noticed the performance changes referenced from #78, but I didn't really test much).
Thanks!
