### ISSUE TITLE
Deprecated use of count()

### ISSUE THREAD

**Issue by StephenWall** [websvnphp/websvn#95]
Running websvn on PHP 7.3 produces the following warning:

`Warning: count(): Parameter must be an array or an object that implements Countable in /usr/local/www/websvn/include/diff_util.php on line 58`

This is due to a [change to the `count()` function in PHP 7.2](https://www.php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types)

I tried a simple change to `strlen()`, but that produced a list of these:
`Notice: Undefined offset: 74 in /usr/local/www/websvn/include/diff_util.php on line 71`

**Comment by ams-tschoening** [comment]
Looking at the `if` using `strlen` as well, using that seems to be the correct approach to me as well. Can't find if `count` did something else in earlier version of PHP, which might explain the difference in these two implementations. Maybe `count` didn't work at all for a long time already in that context and might have returned `0` or such always?

Besides that, how about changing that function to always use the PHP-implementation? It seems like the current additional implementation is some performance optimisation, but things are already 9 years old and I don't see any explanation in the docs. Maybe that optimisation isn't needed anymore at all?

**Comment by michael-o** [comment]
@ams-tschoening I agree here, but the levenstein code (at least the wrapper) hasn't been touched for years: https://github.com/php/php-src/commits/5d6e923d46a89fe9cd8fb6c3a6da675aa67197b4/ext/standard/levenshtein.c

**Comment by ams-tschoening** [comment]
@michael-o My argument is more like CPUs have gotten more powerful since 2010, when things have been implemented in WebSVN. So how slow the PHP-implementation might still be currently, if at all, it simply might not be a problem anymore worth dealing with two different code paths.

Besides that, I might have a clue about what the actual problem is. The following reads like counting the number of characters in the string:

    $n = count($str1);
    $m = count($str2);

But the following clearly is creating an array of individual words and that's what the docs of the function say as well:

    $l1 = explode(' ', $str1);
    $l2 = explode(' ', $str2);

https://www.php.net/manual/en/function.explode.php

The following loops are iterating based on the number of characters, but are accessing with such index the array of words:

    for ($i = 1; $i < $n + 1; $i++) {
    [...]
    $c = ($l1[$i - 1] == $l2[$j - 1])

Of course it's pretty likely that there are more characters than words in the given strings, hence the error message after changing to `strlen`. Maybe `count` simply did count words instead of characters in the past? That would explain as well why `strlen` and `count` are both used in this function already. So things might be as simple as switching order of statements and what to count on:

	$l1 = explode(' ', $str1);
	$l2 = explode(' ', $str2);

	$n = count($l1);
	$m = count($l2);
	$d = array_fill(0, $n + 1, array_fill(0, $m + 1, 0));

	for ($i = 1; $i < $n + 1; $i++) {
		$d[$i][0] = $i;
	}
	for ($j = 1; $j < $m + 1; $j++) {
		$d[0][$j] = $j;
	}

@StephenWall I've uploaded an UNTESTED PR, please give it a try and modify as needed.

**Comment by michael-o** [comment]
@ams-tschoening agree. @StephenWall please give it a try.

**Comment by StephenWall** [comment]
No joy:

> ( ! ) Notice: Undefined offset: 74 in /usr/local/www/websvn/include/diff_util.php on line 74

The offset (74) is one more than the number of non-whitespace sequences ('words') in the lines that are being compared.  (The `line 74` is strictly coincidental.)

Line 74 is this:
`	$c = ($l1[$i - 1] == $l2[$j - 1]) ? 0 : strlen($l1[$i - 1]) + strlen($l2[`**`$i`**` - 1]);`

Note the bold `$i`: `$i` is the `$l1` index, not the `$l2` index.  Correcting that to `$j` after applying the patch looks to fix things.

Thanks for looking into this.

**Comment by ams-tschoening** [comment]
Damn, so count still works like it did in the past. :-) I've applied your change and merged things to master, thanks!
