### ISSUE TITLE
Move dependencies from PEAR to Composer

### ISSUE THREAD

**Issue by marcovtwout** [websvnphp/websvn#97]
The websvn installation docs still require pear and a few packages. Citation from https://websvnphp.github.io/docs/install.html

> apt-get install php-pear
> pear channel-discover pear.geshi.org
> pear install Archive_Tar
> pear install geshi/geshi
> pear install Text_Diff

I know pear is not deprecated, but perhaps these dependencies can be moved to composer, being more future proof?

The three packages should all be available on packagist:
- https://packagist.org/packages/geshi/geshi
- https://packagist.org/packages/pear/archive_tar
- https://packagist.org/packages/pear/text_diff

(for more info see https://stackoverflow.com/questions/34199824/what-is-the-difference-between-pear-and-composer)

**Comment by michael-o** [comment]
Would that require any code changes?

**Comment by marcovtwout** [comment]
My guess is you only need to register the Composer autoloader, perhaps remove existing calls to require/include.

> require __DIR__ . '/vendor/autoload.php';

See https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by michael-o** [comment]
The nice thing about PEAR is that we don't have any trace of it in the code. It just works when all deps are installed via PEAR.
This change looks like it requires a switch between composer and pear, doesn't it?

**Comment by marcovtwout** [comment]
That's true, but that could be achieved with a simple bit of code like:

```php
// Register Composer autoloader if available.
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
}
```

Users can still choose between using PEAR and Composer, and code will remain backwards compatible. New users will probably prefer to install extensions with a simple `composer install --no-dev`, instead of installing the pear binary and installing the packages manually.

**Comment by slimtim** [comment]
I strongly support this feature request from @marcovtwout. Being able to install the dependencies through Composer would be very convenient.

**Comment by ams-tschoening** [comment]
Supporting Composer and PEAR at the same time seems like unnecessary maintenance overhead: Includes would need to handle each of them, the docs would at least need to additionally document dependencies for PEAR, things would need to be tested with each of them etc. Looking at #98, things don't seem to get better maintainable this way as well.

It looks like that really a decision should be made in favour of one of the both package managers and while I don't have too much experience with the PHP ecosystem, I mostly see Composer being used in projects I come across as well.

**Comment by slimtim** [comment]
I agree that supporting both package managers is inefficient and unnecessary. Composer is the de facto standard for managing packages in PHP nowadays. PEAR is rarely used, especially in new PHP projects. 

This SO post outlines some of the reasons to use Composer rather than PEAR. It was written in 2015 and since then Composer has become even more widely adopted by the PHP community.
https://stackoverflow.com/questions/34199824/what-is-the-difference-between-pear-and-composer

I would definitely recommend converting to Composer. The needed code changes are trivial and would only involve a few tweaks to the PR I submitted.

**Comment by michael-o** [comment]
I will look at this a bit later. PEAR seems so easy to use that I don't want to impose more than necessary to the user.

**Comment by slimtim** [comment]
Composer is as easy, or even easier, to use compared to PEAR. Installing packages through Composer is a matter of running a single command, `composer install` -- or `composer update` to update the packages. 

Unlike PEAR, Composer handles dependency management. Since PEAR installs packages globally, if you have a project that relies of version 1 of a library and another project that relies on version 2 of that same library you're out of luck. This isn't a problem with Composer since it installs the libraries on a per-project basis.

**Comment by michael-o** [comment]
@slimtim But this has to happen at install time of WebSVN, right?

**Comment by slimtim** [comment]
You'd run `composer install` in place of the various PEAR install commands, which would happen after fetching and unpacking the WebSVN source code.

**Comment by michael-o** [comment]
@slimtim Alright, the reason why I am asking is because I am the FreeBSD port maintainer of WebSVN and there are some constraints that ports are not allowed to have network access during the build, only the build system has.

**Comment by michael-o** [comment]
I have now merged the PR making this possible, but unwilling to remove PEAR support unless someone provides a solution for this: https://github.com/websvnphp/websvn/pull/98#issuecomment-719955860

**Comment by ams-tschoening** [comment]
I've read the linked comment, but what's the difference between PEAR and Composer on your case? From my perspective in both cases the user needs to run commands. Is the difference that you know which things to install automatically because it's documented for PEAR, but not for Composer? Or is the problem that you already have packages for PEAR-dependencies which are not available for Composer yet or something completely different?

In general, my feeling is that you simply shouldn't try to keep up with the dependencies at all. There are lot's of apps these days bypassing the OS-package manager in favour of something provided by the concrete runtime used and maintaining things per user. Think of Composer, CPAN, NPM etc. I've even read of some apps providing scripts calling through to something like `composer install` on every startup.

**Comment by michael-o** [comment]
@ams-tschoening There is aconcrete difference: PEAR installs for the entire PHP installation while Composer does in the root of the project to `vendor/`. When you are building up a package you supply a list of files part of that package. You cannot do this with Composer because it is now an implementation detail. But regardless of this, I consider this ticket as obsolete because WebSVN now works with both PEAR and Composer. From our point of view we don't have to migrate anything. We leave the decision to the user.

**Comment by ams-tschoening** [comment]
Guten Tag Michael Osipov,
am Sonntag, 1. November 2020 um 13:31 schrieben Sie:

> [...]But regardless
> of this, I consider this ticket as obsolete because WebSVN now works
> with both PEAR and Composer. From our point of view we don't have to
> migrate anything. We leave the decision to the user.

Then simply close the issue for now until it becomes a problem for us
to maintain PEAR and Composer the same time.

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow

**Comment by michael-o** [comment]
Closing this because we do not impose neither of both. They just have to be available at runtime. I have verified both with a vanilla Jail and it just works.
